========================================
Результат без параметрів: 
No URL passed to function
========================================
Результат з правильною URL: 
Time is:  12:44:04 PM
Date is:  10-29-2020
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/oleh/TPIS/Lab2
collected 4 items

tests/tests.py ..F.                                                      [100%]

=================================== FAILURES ===================================
___________________________ TestClass.test_home_work ___________________________

self = <tests.tests.TestClass testMethod=test_home_work>

    def test_home_work(self):
        # Ваш захист
>       self.assertTrue(home_work(self.date_url))

tests/tests.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

url = 'http://date.jsontest.com/'

    def home_work(url=''):
        # Ваш захист
        r_get = requests.get(url=url)
>       a = r.json()
E       NameError: name 'r' is not defined

app.py:45: NameError
=========================== short test summary info ============================
FAILED tests/tests.py::TestClass::test_home_work - NameError: name 'r' is not...
========================= 1 failed, 3 passed in 1.27s ==========================
